### PR TITLE
Libfreenect2 dev

### PR DESCRIPTION
**Pull request by MFernandezCarmona**
Ok, here is what I've done now:
- forked libfreenect2 and included package.xml to allow native cmake projects. So now it's not a submodule (see instead https://github.com/LCAS/libfreenect2). 

- changed  kinect2_bridge CMakelists.txt back to its original form. No external project, freenect2 should be installed, as it's a build dependency in package.xml. Didn't change to use catkin style dependencies because couldn't make it work. 

- Tested in docker (catkin_make_isolated --install) with sources from both this and libfreenect2 fork

### CODE REVIEW

**Comment by marc-hanheide** [comment]
did you check why this failed? I haven't yet.

**Comment by MFernandezCarmona** [comment]
Yes (I think). Now libfreeenect2 is in another repository, so needs to be released as a deb independently or kinect2_bridge can't find it. In docker worked because I cloned both repos.

**Comment by marc-hanheide** [comment]
Ah, so, I need to put another repo on the buildfarm? Can't so it now, but you can open a respective PR on https://github.com/LCAS/rosdistro/ to first add devel builds. Or I do it tomorrow.

**Comment by MFernandezCarmona** [comment]
I was checking https://github.com/LCAS/rosdistro/blob/master/kinetic/lcas-dist.yaml to see what to change, when I realized I'm not a member of https://github.com/lcas-releases organization.
These releases repositories look like they require knowing some stuff I don't know...
But I'm wiling to get access to it and learn how to add them by myself...

**Comment by marc-hanheide** [comment]
just start adding develop build, i.e. fill the section about source, not release. I'll do the rest.

**Comment by MFernandezCarmona** [comment]
Ok. See the pull request at rosdistro...

**Comment by marc-hanheide** [comment]
retest this please

**Comment by MFernandezCarmona** [comment]
Sorry, can you be more specific?

**Comment by marc-hanheide** [comment]
This is the magic phrase to get Jenkins to retest a PR 😹

**Comment by MFernandezCarmona** [comment]
Now everything makes sense...

**Comment by marc-hanheide** [comment]
This now works. Merge and then rerelease?

**Pull request merged**
